server:
  port: 8080
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      cors:
        allowed-origins: '*'
        allowed-methods: '*'
      exposure:
        include: '*'
      base-path: /manage
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banks_api
    username: root
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
#    to change base url of the backend